### ISSUE TITLE
Storable is not instantiable

### ISSUE THREAD

**Issue by JayGajjar** [bavix/laravel-wallet#141]
Hi
I am getting below error when trying to deposit in user.

```
Code:
$user->deposit(10);

Error:

Illuminate\Contracts\Container\BindingResolutionException: Target [Bavix\Wallet\Interfaces\Storable] is not instantiable. in file /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 978

#0 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Container/Container.php(812): Illuminate\Container\Container->notInstantiable('Bavix\\Wallet\\In...')
#1 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('Bavix\\Wallet\\In...')
#2 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->resolve('Bavix\\Wallet\\In...', Array)
#3 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\Container\Container->make('Bavix\\Wallet\\In...', Array)
#4 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(121): Illuminate\Foundation\Application->make('Bavix\\Wallet\\In...', Array)
#5 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Services/CommonService.php(230): app('Bavix\\Wallet\\In...')
#6 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Objects/EmptyLock.php(28): Bavix\Wallet\Services\CommonService::Bavix\Wallet\Services\{closure}()
#7 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Services/LockService.php(38): Bavix\Wallet\Objects\EmptyLock->get(Object(Closure))
#8 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Services/CommonService.php(248): Bavix\Wallet\Services\LockService->lock(Object(Bavix\Wallet\Services\CommonService), 'addBalance', Object(Closure))
#9 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Services/CommonService.php(178): Bavix\Wallet\Services\CommonService->addBalance(Object(Bavix\Wallet\Models\Wallet), 10)
#10 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Objects/EmptyLock.php(28): Bavix\Wallet\Services\CommonService->Bavix\Wallet\Services\{closure}()
#11 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Services/LockService.php(38): Bavix\Wallet\Objects\EmptyLock->get(Object(Closure))
#12 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Services/CommonService.php(180): Bavix\Wallet\Services\LockService->lock(Object(Bavix\Wallet\Services\CommonService), 'multiOperation', Object(Closure))
#13 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Services/CommonService.php(127): Bavix\Wallet\Services\CommonService->multiOperation(Object(Bavix\Wallet\Models\Wallet), Array)
#14 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Objects/EmptyLock.php(28): Bavix\Wallet\Services\CommonService->Bavix\Wallet\Services\{closure}()
#15 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Services/LockService.php(38): Bavix\Wallet\Objects\EmptyLock->get(Object(Closure))
#16 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Services/CommonService.php(131): Bavix\Wallet\Services\LockService->lock(Object(Bavix\Wallet\Services\CommonService), 'deposit', Object(Closure))
#17 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Traits/HasWallet.php(47): Bavix\Wallet\Services\CommonService->deposit(Object(App\Models\Customer), 10, NULL, true)
#18 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): App\Models\Customer::Bavix\Wallet\Traits\{closure}(Object(Illuminate\Database\MySqlConnection))
#19 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Services/DbService.php(37): Illuminate\Database\Connection->transaction(Object(Closure), 1)
#20 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/bavix/laravel-wallet/src/Traits/HasWallet.php(48): Bavix\Wallet\Services\DbService->transaction(Object(Closure))
#21 /home/waitless/wlm2.dev.waitlessmunch.co.uk/app/Http/Controllers/AuthControllerAPI.php(78): App\Models\Customer->deposit(10)
#22 [internal function]: App\Http\Controllers\AuthControllerAPI->authenticate(Object(Illuminate\Http\Request))
#23 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#24 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('authenticate', Array)
#25 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\AuthControllerAPI), 'authenticate')
#26 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#27 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#28 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 60, '1')
#33 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#36 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#37 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#38 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#39 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#40 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /home/waitless/wlm2.dev.waitlessmunch.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 /home/waitless/wlm2.dev.waitlessmunch.co.uk/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 {main}
```

**Comment by rez1dent3** [comment]
@JayGajjar Hello! Not enough data. Need a version of laravel, php and config laravel wallet

**Comment by JayGajjar** [comment]
```
PHP version | PHP/7.2.25
Laravel version | 6.9.0
```

Wallet Config file :

```
<?php

use Bavix\Wallet\Objects\Bring;
use Bavix\Wallet\Objects\Cart;
use Bavix\Wallet\Objects\EmptyLock;
use Bavix\Wallet\Objects\Operation;
use Bavix\Wallet\Services\ExchangeService;
use Bavix\Wallet\Services\CommonService;
use Bavix\Wallet\Services\ProxyService;
use Bavix\Wallet\Services\WalletService;
use Bavix\Wallet\Services\LockService;
use Bavix\Wallet\Models\Transaction;
use Bavix\Wallet\Models\Transfer;
use Bavix\Wallet\Models\Wallet;
use Bavix\Wallet\Simple\Rate;
use Bavix\Wallet\Simple\Store;

return [
    /**
     * The parameter is used for fast packet overload.
     * You do not need to search for the desired class by code, the library will do it itself.
     */
    'package' => [
        'rateable' => Rate::class,
        'storable' => Store::class,
    ],

    /**
     * Lock settings for highload projects
     *
     * If you want to replace the default cache with another,
     * then write the name of the driver cache in the key `wallet.lock.cache`.
     * @see https://laravel.com/docs/6.x/cache#driver-prerequisites
     *
     * @example
     *  'cache' => 'redis'
     */
    'lock' => [
        'cache' => null,
        'enabled' => false,
        'seconds' => 1,
    ],

    /**
     * Sometimes a slug may not match the currency and you need the ability to add an exception.
     * The main thing is that there are not many exceptions)
     *
     * Syntax:
     *  'slug' => 'currency'
     *
     * @example
     *  'my-usd' => 'USD'
     */
    'currencies' => [],

    /**
     * Services are the main core of the library and sometimes they need to be improved.
     * This configuration will help you to quickly customize the library.
     */
    'services' => [
        'exchange' => ExchangeService::class,
        'common' => CommonService::class,
        'proxy' => ProxyService::class,
        'wallet' => WalletService::class,
        'lock' => LockService::class,
    ],

    'objects' => [
        'bring' => Bring::class,
        'cart' => Cart::class,
        'emptyLock' => EmptyLock::class,
        'operation' => Operation::class,
    ],

    /**
     * Transaction model configuration.
     */
    'transaction' => [
        'table' => 'transactions',
        'model' => Transaction::class,
        'casts' => [],
    ],

    /**
     * Transfer model configuration.
     */
    'transfer' => [
        'table' => 'transfers',
        'model' => Transfer::class,
        'casts' => [],
    ],

    /**
     * Wallet model configuration.
     */
    'wallet' => [
        'table' => 'wallets',
        'model' => Wallet::class,
        'casts' => [],
        'default' => [
            'name' => 'Default Wallet',
            'slug' => 'default',
        ],
    ],
];

```

**Comment by rez1dent3** [comment]
@JayGajjar Launched in docker with your version of php and laravel. Everything works. I think the thing is in the cache, try to reset it.
```php
php artisan config:clear
php artisan clear-compiled
php artisan optimize
php artisan config:cache
```

**Comment by JayGajjar** [comment]
Working now thanks for quick support
